#cloud-config
packages:
- netplan.io
write_files:
  - path: /etc/netplan/eth1.yaml
    content: |
      network:
        version: 2
        ethernets:
          eth1:
            dhcp4: true
  - path: /etc/netplan/eth2.yaml
    content: |
      network:
        version: 2
        ethernets:
          eth2:
            dhcp4: true
runcmd:
  - netplan apply
